### ISSUE TITLE
Upgrade branch 1.0.0-alpha to Angular 5.0.0-alpha+8

### ISSUE THREAD

**Issue by CedX** [dart-league/ng_bootstrap#103]
I've encountered this bug (using `package:ng_bootsrap` 1.0.0-alpha and `package:angular` 5.0.0-alpha+7):
https://github.com/dart-lang/build/issues/1192

It seems to be fixed fixed in `package:angular` 5.0.0-alpha+8. Could you upgrade the Angular dependency and release a new version of your package?

Thanks in advance.

**Comment by luisvt** [comment]
working on it

**Comment by cedx** [comment]
It's also probably time to upgrade Bootstrap stylesheets to v4.0.0 final.
I've opened a [pull request on the `bootstrap_sass`](https://github.com/dart-league/bootstrap_sass/pull/4) repository.
