### ISSUE TITLE
Bs-table column does not support sorting on Number and Date basis !!!

### ISSUE THREAD

**Issue by sandeepkumarsahoo** [dart-league/ng_bootstrap#117]
The bs-column component does not supports sorting on number and date basis.
Its supports sorting on String .

Is it possible to add any customize method/function for sorting on number /Date basis ???

**Comment by jheyne** [comment]
Returning data as Comparable (rather than String) helps:

  Comparable getData(dynamic row, String fieldName) {
    var data = fieldName.split('.').fold(row, _getDataFn);
    if(data is Comparable) {
      return data;
    }
    return data.toString();
  }
