### ISSUE TITLE
Add support to angular 6.0.0-alpha

### ISSUE THREAD

**Issue by lucasdidur** [dart-league/ng_bootstrap#128]
Because ng_bootstrap 1.1.1 depends on angular ^5.1.0 and no versions of ng_bootstrap match >1.1.1 <2.0.0, ng_bootstrap ^1.1.1 requires angular ^5.1.0.
So, because app depends on both ng_bootstrap ^1.1.1 and angular ^6.0.0-alpha, version solving failed.

**Comment by lucasdidur** [comment]
Any release date?

**Comment by luisvt** [comment]
I'm working on it, please check this branch:

https://github.com/dart-league/ng_bootstrap/tree/upgrade-ng-6.0.0-alpha

**Comment by luisvt** [comment]
solved by #130
