### ISSUE TITLE
Upgrade to angular 6.0.1

### ISSUE THREAD

**Issue by avdept** [dart-league/ng_bootstrap#135]
As title says - is there working version with angular 6.0.1 dependency? Currently it uses 6.0.0-alpha

**Comment by luisvt** [comment]
Not yet. I need to upgrade and modify the code, thanks

**Comment by avdept** [comment]
I've upgraded it in fork, but there were some breaking changes in templates, so I had to fix those components which I use. I will try to wrap all changes into PR and submit during couple few days if that will help you

**Comment by avdept** [comment]
@luisvt I've submitted draft PR here - https://github.com/dart-league/ng_bootstrap/pull/136. However demo app does not want to build throwing errors like
```
pub-cache/hosted/pub.dartlang.org/serializable-0.13.0/lib/generator.dart:39:117: Error: The getter 'type' isn't defined for the class 'TypeParameterElement'. - 'TypeParameterElement' is from 'package:analyzer/dart/element/element.dart' ('../../../.pub-cache/hosted/pub.dartlang.org/analyzer-0.40.4/lib/dart/element/element.dart').Try correcting the name to the name of an existing getter, or defining a getter or field named 'type'.
```

If you know how to fix that - I would appreciate, as I could test everything by myself
