### ISSUE TITLE
Typeahead optionField works if the source is a Map but not a user-defined object

### ISSUE THREAD

**Issue by wz2b** [dart-league/ng_bootstrap#24]
I have a situation where I'm trying to use a typeahead with an actual object.  In my case the object is named "Tag" and it has a number of fields like 'name' and 'description.'  My asynchronous loader returns an Iterable<Tag>.

This doesn't work with [optionField] though because the Typeahead tries to do this:

`_itemString(item, String optionField) => item is String ? item : item[optionField];`

but it's an object, so it needs to be accessed as item.field ... for example, in my case, item.name but _not_ item['name']

I'm not sure how one would fix this in a way that doesn't compromise performance.  I think it would be OK to say that if you're going to do this you need to also pass in the type via the unimplemented runtimeType input.

Another option would be to use [inputFormatter] and simply pass in a function that takes in any object and returns a string.  That would be a little less automatic than just specifying a field name in [optionField] but it would be easy to implement and very flexible.

**Comment by wz2b** [comment]
Pull request #25 would fix this.

**Comment by wz2b** [comment]
I was thinking, there's another way to solve this that could take better advantage of the dart language.

What if we made an interface TypeaheadModel  that defines a method getBootstrapControlDisplayString()  (I don't know what to name it, so I want to be descriptive here).  Then typeahead could examine the source object for that interface and if it's implemented by the object call it.

I woudln't want to pollute my objects this way normally but maybe a mix-in approach would work.

Does that sound better or worse than just declaring a formatting function as an @Input ?

**Comment by luisvt** [comment]
check #29
