### ISSUE TITLE
Weird code in DatePickerPopup

### ISSUE THREAD

**Issue by zoechi** [dart-league/ng_bootstrap#26]
https://github.com/dart-league/ng_bootstrap/blob/develop/lib/components/datepicker/date_picker_popup.dart#L38

This method doesn' t seem to do anything. It just updates a local variable, but no side effect that persists when the method exists.

**Comment by zoechi** [comment]
It also doesn't seem to work for me. The browser hung completely when I used it. I might be able to investigate myself in a few days.

**Comment by luisvt** [comment]
let me check, I think it converted string to date.

**Comment by zoechi** [comment]
but it doesn't do anything with the result. The local variable it assigns to isn't available anymore when the method exits.
