### ISSUE TITLE
Typeahead does not work with a list which is an Input()

### ISSUE THREAD

**Issue by sturmf** [dart-league/ng_bootstrap#44]
Hi I try to embed a typeahead in my component and am stuck with it loading my initial list.
Everything works as expected if the list is statically initialized but it does not load the initial values if the list is an input field of the parent component.

E.g. I have the list defined as following:

`@Input() List<Person> persons;`

 and use it in the component as following:

```
    <bs-typeahead [(ngModel)]="selectedObj"
                  [source]="persons"
                  [(selectedItem)]="selectedItemObj"
                  (selectedItemChange)="addAssistant($event)"
                  optionField="first_name">
    </bs-typeahead>
```

This means that the list is empty during the construction of the parent and embeded component. It gets eventually filled in the ngOnInit call. Unfortunately this does not update the typeahead component and the dropdown is empty until I do the first search.

Any ideas what I am doing wrong?

**Comment by luisvt** [comment]
Could you show me a full example?

Have you tried to create an event emitter for the variable `persons`, in that way the dom will know when it is updated. Somthing like this:

``` dart
List<Person> _persons;

get persons => _persons;

@Input() set persons(List<Person> persons) {
  _persons = persons;
  personsChange.emit(persons);
}

@Output() EventEmitter<List<Person>> personsChange = new EventEmitter();
```

**Comment by sturmf** [comment]
Thanks for the suggestion. Unfortunately it still behaves the same :-( The source of the component is here: https://github.com/sturmf/regatta-angular2/blob/ng_bootstrap_support/frontend/lib/event_assistants_list_component.dart

I'll try to get a live version setup somewhere.

**Comment by sturmf** [comment]
Hmm I just saw that I get the following error from pub serve, maybe it has something with this to do?

No matching file found for the following Angular2 transformer entry_points:
- web/index.dart
- web/components/accordion/main.dart
- web/components/alert/main.dart
- web/components/buttons/main.dart
- web/components/carousel/main.dart
- web/components/collapse/main.dart
- web/components/datepicker/main.dart
- web/components/dropdown/main.dart
- web/components/file_upload/main.dart
- web/components/modal/main.dart
- web/components/pagination/main.dart
- web/components/progress/main.dart
- web/components/rating/main.dart
- web/components/tabs/main.dart
- web/components/table/main.dart
- web/components/tabsx/main.dart
- web/components/timepicker/main.dart
- web/components/tooltip/main.dart
- web/components/typeahead/main.dart

**Comment by zoechi** [comment]
@sturmf you can safely ignore that warnings if the entry_points are not defined in your `pubspec.yaml`
These warnings should only report missing entry_points from your current project, but the transformer somehow picks up the entry_points from dependency packages which it shouldn't
but this results in entry_points from other packges being warned about

**Comment by zoechi** [comment]
@luisvt I had better experience in overall with examples when I put them in a sub-project
like a new project in `ng_bootstrap/example` (not `examples` because it's a pub known folder name)
create a `pubspec.yaml` file there with a path dependency to the parent folder for `ng_bootstrap`

This way example-related stuff can be kept out from the main `pubspec.yaml` file.

Just my 2c

_The warning mentioned above are by no means a fault of ng_bootstrap_. It's a known Angular2 transformer issue.

**Comment by luisvt** [comment]
Yes, I was considering that, thanks

**Comment by sturmf** [comment]
Hey luisvt thanks again for the code review. Since my code now is fully transformed to an asynchronous version I can close this issue.
