### ISSUE TITLE
BootStrap 4 alpha 4 aesthetically breaks a few widgets

### ISSUE THREAD

**Issue by sandrobilbeisi** [dart-league/ng_bootstrap#47]
BootStrap 4 alpha 4 aesthetically breaks a few widgets

Some widgets which appear to be ok with Bootstrap 4 Alpha 3 
specifically : checkbox , radio , input groups , calendar , tooltip , select2

have significative visual glitches and layout problems after replacing main CSS with
BootStrap 4 alpha 4

**Comment by luisvt** [comment]
Could you please send an image?

**Comment by sandrobilbeisi** [comment]
correct select2 autocomplete BootStrap 4 alpha 3:
![screen shot 2016-10-11 at 20 23 10](https://cloud.githubusercontent.com/assets/755824/19282995/a9123cfe-8ff0-11e6-8cf0-262c548e5020.png)
broken select with BootStrap 4 alpha 4:
![screen shot 2016-10-11 at 20 23 02](https://cloud.githubusercontent.com/assets/755824/19283017/bdda7494-8ff0-11e6-9212-bb719d605514.png)

**Comment by sandrobilbeisi** [comment]
correct tooltip autocomplete BootStrap 4 alpha 3:
![screen shot 2016-10-11 at 20 22 41](https://cloud.githubusercontent.com/assets/755824/19283059/d58119b8-8ff0-11e6-8cbb-b5fd4b38b273.png)

broken tooltip with BootStrap 4 alpha 4:
![screen shot 2016-10-11 at 20 22 51](https://cloud.githubusercontent.com/assets/755824/19283069/df8ffeb0-8ff0-11e6-96c1-cce3fce71e74.png)

**Comment by sandrobilbeisi** [comment]
correct pagination autocomplete BootStrap 4 alpha 3:
![screen shot 2016-10-11 at 20 21 44](https://cloud.githubusercontent.com/assets/755824/19283103/03348fde-8ff1-11e6-8a5a-608051e77183.png)

broken pagination with BootStrap 4 alpha 4:
![screen shot 2016-10-11 at 20 21 55](https://cloud.githubusercontent.com/assets/755824/19283091/f4508770-8ff0-11e6-9bcf-a71d604d2841.png)

**Comment by sandrobilbeisi** [comment]
correct dropdown autocomplete BootStrap 4 alpha 3:
![screen shot 2016-10-11 at 20 21 21](https://cloud.githubusercontent.com/assets/755824/19283162/35f5cbcc-8ff1-11e6-9787-ada6f8a8f292.png)
broken dropdown with BootStrap 4 alpha 4:
![screen shot 2016-10-11 at 20 21 14](https://cloud.githubusercontent.com/assets/755824/19283159/32d4a5d0-8ff1-11e6-8c94-46ba93d3949b.png)

**Comment by sandrobilbeisi** [comment]
correct date popup autocomplete BootStrap 4 alpha 3:
the popup is NOT visible at the start, but only after invoking it by clicking
![screen shot 2016-10-11 at 20 21 03](https://cloud.githubusercontent.com/assets/755824/19283221/5e238972-8ff1-11e6-8d8d-21352c94f5d8.png)

broken date popup with BootStrap 4 alpha 4:
the popup is visible at the start
![screen shot 2016-10-11 at 20 20 55](https://cloud.githubusercontent.com/assets/755824/19283228/628d6adc-8ff1-11e6-8d0e-f5f7814adcf8.png)

**Comment by sandrobilbeisi** [comment]
last but not least, there are some minor stylistic differences which are not bugs but may affect usability and expectations : 
correct buttons BootStrap 4 alpha 3:
![screen shot 2016-10-11 at 20 20 18](https://cloud.githubusercontent.com/assets/755824/19283376/e0f501f0-8ff1-11e6-92a4-678fd19180eb.png)

changed buttons with BootStrap 4 alpha 4:
![screen shot 2016-10-11 at 20 20 05](https://cloud.githubusercontent.com/assets/755824/19283390/eaa9f9f8-8ff1-11e6-8620-1763b655ee7f.png)

**Comment by luisvt** [comment]
wow, that's cool. thanks a lot. I will try now.

**Comment by luisvt** [comment]
Did you add `bootstrap 4` using cdn?

If that the case, the reaseon styles are broken is because `ng_bootstrap` doesn't use `bootstrap.css` directly. It compiles, the file [style.scss](https://github.com/dart-league/ng_bootstrap/blob/gh-pages/web/style.scss) which imports [all.scss](https://github.com/dart-league/ng_bootstrap/blob/gh-pages/web/style.scss#L4) which internally imports [bootstra.scss](https://github.com/dart-league/ng_bootstrap/blob/develop/lib/all.scss#L4). So that your problem is that you are missing some styles.

**Comment by sandrobilbeisi** [comment]
I'm going to try a local bootstrap.scss and get back to you ...

**Comment by luisvt** [comment]
version `0.5.1` has been released, this one contains `bootstrap_sass-4.0.0-alpha.5` and it doesn't present any of the errors showed before. Because of that, I'm going to close this issue.

Let me know if it works for you.
