### ISSUE TITLE
Cannot load web fonts of Font Awesome

### ISSUE THREAD

**Issue by FranklinYu** [dart-league/ng_bootstrap#59]
### issue

When I add Font Awesome icons like [thumbs up](http://fontawesome.io/icon/thumbs-o-up/):

```html
<i class="fa fa-thumbs-o-up" aria-hidden="true"></i>
```

and serve with `pub serve`, my Dartium and Chrome tries to request (a very weird link) http://localhost:8080/packages/ng_bootstrap/packages/font_awesome/fonts/fontawesome-webfont.woff2?v=4.6.3 which returns a "file not found":

```text
[web] GET packages/ng_bootstrap/packages/font_awesome/fonts/fontawesome-webfont.woff2 → Could not find asset ng_bootstrap|lib/packages/font_awesome/fonts/fontawesome-webfont.woff2.
```

### more info

A working example can be created with:

1. generate an Angular project with [Stagehand](https://pub.dartlang.org/packages/stagehand)'s `web-angular-quickstart` template;
2. follow steps 2 and 3 in section "Getting Started" in README (skip step 4 since no new directive here);
3. in template of `AppComponent` add a random icon (like the "thumb up" I mentioned before).
4. `pub serve` and view it in browser.

Then I see three "file not found" error: `.woff2` file, its fallback `.woff` file, and further fallback `.ttf` file. My environment (latest stable except OS):

* Dart SDK with Dartium: 1.21.0
* Chrome: 55.0.2883.87, Firefox 50.1.0
* Stagehand: 1.0.19
* OS X: El Capitan

Remarkably, vanilla Font Awesome works: following the same steps as stated before, replacing step 2 with instructions in [Font Awesome package](https://pub.dartlang.org/packages/font_awesome), does not give any errors. This is actually expected, since it hits http://localhost:8080/packages/font_awesome/fonts/fontawesome-webfont.woff2?v=4.6.3 which seems more reasonable than the URL before. I guess the issue lies in the "double packages" part, that is `/packages/ng_bootstrap/packages/font_awesome/`. It can be `ng_bootstrap`, Angular, or `pub`.

### update

A work-around is to create a symbolic link from
```text
.pub/deps/debug/ng_bootstrap/lib/packages/font_awesome
```
to

```text
~/.pub-cache/hosted/pub.dartlang.org/font_awesome-4.6.3/lib/
```

### update 2

Chrome does produce the errors, but it also hits (miraculously) http://localhost:8080/packages/font_awesome/fonts/fontawesome-webfont.woff2?v=4.6.3 which is the correct URL. The timeline suggests that this may be a fallback for those three 404s. This behavior does not occur on Dartium yet (maybe the browser kernel is outdated?). Dartium does show the icon, probably by searching build-in fonts or system fonts. Unfortunately Firefox neither gets to the fallback nor shows the icon.

**Comment by FranklinYu** [comment]
? What's up? It works, why reopen?

**Comment by luisvt** [comment]
When the app is run with intellij run button instead doing `pub serve` in console the browser path has a different root. That causes the icons not being showed. I think now is corrected
