### ISSUE TITLE
Compatibility?

### ISSUE THREAD

**Issue by jrpruitt** [dart-league/ng_bootstrap#63]
**When testing ng_bootstrap, I get the following error:**
Incompatible version constraints on intl:
- angular2 2.2.0 depends on version >=0.13.0 <0.15.0
- angular2_components 0.2.2 depends on version ^0.14.0
- ng_bootstrap 0.1.0 depends on version ^0.13.0

**I get this with both WebStorm 2016.3.3 and IntelliJ IDEA 2016.3.4.**
**Dart SDK is 1.22.0**

**My pubspec.yaml:**
name: testNG
description: A Dart app that uses Angular 2
version: 0.0.1
environment:
  sdk: '>=1.19.0 <2.0.0'
dependencies:
  angular2: '>=2.2.0 <2.3.0'
  angular2_components: '>=0.2.2 <0.3.0'
  ng_bootstrap: any  **<--- Only added this line to default yaml that works fine.**

dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
transformers:
- angular2:
    platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    platform_pipes:
    - 'package:angular2/common.dart#COMMON_PIPES'
    entry_points: web/main.dart
- dart_to_js_script_rewriter

I've done searches and found no solution for getting this to work on the current SDK and Angular2 version.

Please Advise,
John Pruitt

**Comment by luisvt** [comment]
new version of `ng_bootstrap` should solve the problem please test it
