### ISSUE TITLE
Datepicker does not read a date properly.

### ISSUE THREAD

**Issue by avstudios** [dart-league/ng_bootstrap#68]
I've copied an example of date pickers from ```http://dart-league.github.io/ng_bootstrap/build/web/index.html``` page.
Then changed the dates to:
```DateTime dt = new DateTime.now().add(new Duration(days: -1000));```
```DateTime dt2 = new DateTime.now().add(new Duration(days: -2000));```
And the datapicker show the current date time insted of the past date.
If I delay creating the DataTime object the component works fine.

**Comment by luisvt** [comment]
could you show me a full code example?

**Comment by avstudios** [comment]
[untitled8.zip](https://github.com/dart-league/ng_bootstrap/files/1067885/untitled8.zip)

**Comment by luisvt** [comment]
thanks, I'll take a look.
