### ISSUE TITLE
Tooltip Positioning in Table

### ISSUE THREAD

**Issue by sambbaron** [dart-league/ng_bootstrap#76]
I am trying to add a tooltip to the content of a table cell in a `<td>` element. On my first try, the tooltip was positioned against the body. Then I debugged the position methods and saw that `_parentOffsetEl` is looking for the first non-statically positioned element, so I wrapped the content of the table cell in a `<div>` with `position:relative`. That caused an error to be thrown in `_position`, line 31, because it is trying to set the `top` property of an immutable Rectangle. At first, `offsetParentBCR` is set as a Position on line 27, but then it is overridden as a Rectangle in line 30.

>EXCEPTION: NoSuchMethodError: Class 'Rectangle' has no instance setter 'top='.
Receiver: Instance of 'Rectangle'
Tried calling: top=233
STACKTRACE: 
dart:core                                                   Object.noSuchMethod
package:ng_bootstrap/core/position.dart 31:21               _position
package:ng_bootstrap/core/position.dart 50:50               positionElements
package:ng_bootstrap/components/tooltip/tooltip.dart 99:15  BsTooltipComponent.show.<fn>

**Comment by luisvt** [comment]
thanks, I'll check the error as soon I can.
