### ISSUE TITLE
DDC problem in Pagination (0.8.3)

### ISSUE THREAD

**Issue by rbishop-bah** [dart-league/ng_bootstrap#79]
Did not see the problem in 0.8.2.  We do not use pagination yet in our app, but the app won't run due to this error.

![image](https://user-images.githubusercontent.com/3227777/29921393-6665b3a8-8e1f-11e7-9d5e-710159b5081f.png)

**Comment by luisvt** [comment]
I think this issue is already solved, I cannot reproduce it anymore.

**Comment by rbishop-bah** [comment]
We're able to run the app again under 0.8.4.

**Comment by luisvt** [comment]
cool, I'm gonna close this issue then.
