### ISSUE TITLE
Any update on new components 

### ISSUE THREAD

**Issue by nni123** [dart-league/ng_bootstrap#81]
I like the existing dart components but repo is not very active, so checking your future plans.

Are you going to add more components or update existing Grid/Table with additional features e.g. fix headers etc?

Thanks

**Comment by luisvt** [comment]
yes, I'm updating and adding components. However it takes time and I don't have any estimates.

What problems are you having with Grid/Table?

**Comment by rbishop-bah** [comment]
Is Popover on the add soon list?

**Comment by luisvt** [comment]
Not yet, but if you need it I can add it

**Comment by rbishop-bah** [comment]
I will need it Q4.  Thanks!

**Comment by nni123** [comment]
I am looking at DataTable with Scroll. 

Data scrolling with a fixed header...any plan to add horizontally or vertically or both (vertical will do for now)...  

Thanks

**Comment by luisvt** [comment]
there are plans, but there is no time.

**Comment by luisvt** [comment]
Data scrolling with a fixed header added on release 1.0.0
