### ISSUE TITLE
Look at pkg/peanut for updating your gh-pages branch

### ISSUE THREAD

**Issue by kevmoo** [dart-league/ng_bootstrap#83]
https://pub.dartlang.org/packages/peanut

You can put your example code in `example` and then do `peanut -d example`

Is nice!

**Comment by luisvt** [comment]
I'm not able to use the peanut package since it requires that `ng_bootstrap` have dependencies on `dson`. Even thought I cound add that dependency, I would still get some errors doubt to peanut will try to use `pubspec.yaml` file from root directory instead the one from `example` directory.

**Comment by kevmoo** [comment]
Ah! So you want to be able to run it within the subdirectory.

Good feature request...

You could also add a dev dependency to `dson` and run it as `peanut -d example`.

See https://github.com/dart-lang/markdown as an example

**Comment by luisvt** [comment]
yes, I did added dson as dev dependency also. However it still didn't work.

**Comment by luisvt** [comment]
I think it was because I need to add the entry points to the angular transformer, but that will break others people code. That's why I didn't want to do that.

**Comment by luisvt** [comment]
what I did at the end was to fallow this:

https://gist.github.com/cobyism/4730490

**Comment by kevmoo** [comment]
Another option: https://github.com/dart-lang/mono_repo

We're making tools so it's easier to have multiple packages in one repo.

**Comment by luisvt** [comment]
This is not needed anymore since github now allows to use docs folder from master repo as the source for github pages.
