### ISSUE TITLE
Publish 0.9.0?

### ISSUE THREAD

**Issue by rbishop-bah** [dart-league/ng_bootstrap#88]
Any chance we can get 0.9 published on pub.dartlang (even as a dev release if necessary)?

We're having some issues grabbing it from GitHub in our automated builds and we've started using popover.

**Comment by luisvt** [comment]
Sorry I'm on vacation far from my computer, I'll be back next week. I'll try to publish soon if I got some time.

**Comment by rbishop-bah** [comment]
OK, thanks!

**Comment by luisvt** [comment]
it's published
