### ISSUE TITLE
Datepicker is unusable

### ISSUE THREAD

**Issue by BorisNaguet** [dart-league/ng_bootstrap#90]
Hello,

I thought that I had an issue with my code, but you can try on your example website. 
Nothing seems to works for me.

**Comment by luisvt** [comment]
I just checked using Firefox and it is working as expected

**Comment by BorisNaguet** [comment]
Thanks for watching.

My issues:
* happen in inline and pop-up ex.
* happen in FF and Chrome (I switched to en_US locale in Chrome too to be sure)
* happen on the demo website and on my own tests

Issues are:
1.  clicking on left/right arrow doesn't update month that is shown on the calendar (still November).
Though It changes selected date to:

> Selected date is: 2017-10-01 00:00:00.000

and

> Selected date is: 2017-12-01 00:00:00.000

If I click on 20 it then goes to 

> Selected date is: 2017-11-20 00:00:00.000

Which makes sense because, it's still written "November"

Also, clicking more than once on these arrows doesn't goes further that October/December

2. When I try to select year -> month -> day, After year/month worked ok, the shown month is not updated, so clicking on a day reselect 2017-11

3. Sometime in that same case the year (month) gets updated (once) and then I'm stuck on that one.

4. If the 1st thing that I do on the widget (after page load) is clicking on 2017 to change year and then 2015 I get:
![screen shot 11-16-17 at 07 52 pm](https://user-images.githubusercontent.com/1359247/32909931-39d034dc-cb08-11e7-9bf5-05df7f90c9b8.PNG)


If you can't reproduce, any of them, it's very strange (I'll ask someone else to test) :-(

**Comment by luisvt** [comment]
thanks, I just was able to reproduce the error, I'll take a look into it
